spring.application.name=SpringBootFirstEx

spring.datasource.url="jdbc:postgressql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=Preto2210
spring.jpa.hibernate.ddl-auto=update

spring.jpa.propertis.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true